'use client';
import BottomNavigation from '@/components/navigation/bottom-navigation';
import SideBar from '@/components/sidebar/sidebar';
// import type { Metadata } from 'next';
import { redirect } from 'next/navigation';
import { useSelector } from 'react-redux';
import { RootState } from '../store/store';
// export const metadata: Metadata = {
//     title: 'Something Unique - Login',
//     description: 'Generated by create next app',
// };

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    const authToken = localStorage?.getItem('authToken');
    if (!authToken) {
        redirect('/register');
    }
    const { viewType } = useSelector(
        (state: RootState) => state.view
    );
    return (
        <div className="p-1 sm:p-3 h-screen w-screen flex items-center justify-center gap-10 bg-background divide-x">
            <div
                className={`h-full ${
                    viewType === 'default'
                        ? 'md:w-3/4 w-full'
                        : 'w-3/5 '
                } flex flex-col gap-5 transition-all duration-500 ease-in-out`}
            >
                <div
                    className={`sm:h-[92%] h-full rounded-xl overflow-scroll pb-5 scrollbar-hide relative`}
                >
                    {children}
                </div>
                <div
                    className={`h-[8%] absolute sm:relative ${
                        viewType !== 'default' ? 'left-4' : 'right-4'
                    } bottom-4 right-4 z-50 rounded-xl w-fit`}
                >
                    <BottomNavigation />
                </div>
            </div>
            <div
                className={`${
                    viewType !== 'default'
                        ? 'absolute top-0 left-0 inset-0'
                        : 'hidden sm:block'
                } md:relative  md:hover:bg-secondary/20 bg-background duration-150 flex-1 h-full md:rounded-xl overflow-scroll scrollbar-hide`}
            >
                <SideBar />
            </div>
        </div>
    );
}
