'use client';
import BottomNavigation from '@/components/navigation/bottom-navigation';
import SideBar from '@/components/sidebar/sidebar';
// import type { Metadata } from 'next';
import { redirect } from 'next/navigation';
import { useSelector } from 'react-redux';
import { RootState } from '../store/store';
import { parseJwt } from '@/lib/jwt';
import React, { Suspense } from 'react';
import { JwtPayload } from '@/types/auth.types';
// export const metadata: Metadata = {
//     title: 'College Point - Login',
//     description: 'Generated by create next app',
// };

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    const [payload, setPayload] = React.useState<JwtPayload | null>(null);
    React.useEffect(() => {
        const token = window?.localStorage.getItem('authToken');
        if (!token || token === 'undefined') {
            redirect('/register');
        } else {
            const data = parseJwt(token);
            if(data === null) {
                window?.localStorage.removeItem('authToken');
                redirect('/register');
            }
            setPayload(data);
        }
    }, []);
    const { viewType } = useSelector(
        (state: RootState) => state.view
    );
    return (
        <div className="p-1 sm:p-3 h-screen w-screen flex items-center justify-start gap-10 bg-background divide-x">
            <div
                className={`h-full ${
                    viewType === 'default'
                        ? 'lg:w-3/4 w-full'
                        : 'w-3/5 '
                } flex flex-col gap-5 transition-all duration-500 ease-in-out`}
            >
                <div
                    className={`lg:h-[92%] h-full rounded-xl overflow-scroll pb-5 scrollbar-hide relative`}
                >
                    <Suspense>{children}</Suspense>
                </div>
                <div
                    className={`h-[8%] fixed lg:relative ${
                        viewType !== 'default'
                            ? 'lg:left-4 right-4'
                            : 'right-4'
                    } bottom-4 left-4 z-50 rounded-xl w-fit`}
                >
                    <Suspense>
                        <BottomNavigation payload={payload} />
                    </Suspense>
                </div>
            </div>
            <div
                className={`${
                    viewType !== 'default'
                        ? 'fixed top-0 left-0 inset-0'
                        : 'hidden lg:block'
                } md:relative  md:hover:bg-secondary/20 bg-background duration-150 flex-1 h-full md:rounded-xl overflow-scroll scrollbar-hide`}
            >
                <SideBar />
            </div>
        </div>
    );
}
