'use client';
import BottomNavigation from '@/components/navigation/bottom-navigation';
import SideBar from '@/components/sidebar';
// import type { Metadata } from 'next';
import { redirect } from 'next/navigation';
import { useSelector } from 'react-redux';
import { RootState } from '../store/store';
// export const metadata: Metadata = {
//     title: 'Something Unique - Login',
//     description: 'Generated by create next app',
// };

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    const authToken = localStorage?.getItem('authToken');
    if (!authToken) {
        redirect('/register');
    }
    const { viewType } = useSelector(
        (state: RootState) => state.view
    );
    return (
        <div className="p-3 h-screen w-screen flex items-center justify-center gap-10 bg-background divide-x">
            <div
                className={`h-full ${
                    viewType === 'default' ? 'w-3/4' : 'w-3/5 '
                } flex flex-col gap-5 transition-all duration-500 ease-in-out`}
            >
                <div
                    className={`h-[92%] rounded-xl overflow-scroll pb-5 scrollbar-hide relative`}
                >
                    {children}
                </div>
                <div className="h-[8%] rounded-xl">
                    <BottomNavigation />
                </div>
            </div>
            <div className="hover:bg-secondary/20 duration-150 flex-1 h-full rounded-xl">
                <SideBar />
            </div>
        </div>
    );
}
