export const NO_POST_MESSAGES = [
    'Silence so loud, you can hear the existential dread. Post something, maybe? 🖤',
    'This page is emptier than your fridge during finals. 🍕❌',
    'Wow, even ghosts don’t haunt this space. 👻 Start the action!',
    'No posts? Guess the apocalypse started early. ☠️💬',
    'Quieter than your ex’s replies. 👀 Say something!',
    'Looks like the procrastination plague hit everyone hard. Post and recover! 🦠💻',
    'No posts? It’s giving ‘dead inside’ vibes. 🪦 Fix it!',
    'So empty, it’s almost poetic. But not really. Post, poet. ✍️',
    'If awkward silences were a page, this would be it. Break it. 🤫',
    'This page is a metaphor for my GPA—absolutely nothing here. 🫠 Start the party!',
];

export const USERNAME_NOT_AVAILABLE_MSG = [
    'Taken. Looks like someone beat you to it, champ.',
    'Nope, that username is in a better place.',
    'Username’s gone. Someone swiped it like the last slice of pizza.',
    'That username is on a permanent vacation.',
    'Sorry, that username already has a date with destiny.',
    'Not available. Your username got eaten by the void.',
    'That name’s in use. It’s the digital equivalent of a sold-out show.',
    "Username's out. Maybe it's hiding, maybe not.",
    'Nope, someone else already called dibs on that username.',
    "That username's off the market, buddy.",
];

export const USERNAME_AVAILABLE_MSG = [
    "Bingo! It's all yours. You just scored a digital jackpot.",
    'It’s yours! Like finding money in an old coat pocket.',
    'That username’s free. You’re basically royalty now.',
    'Ding ding! Your username’s ready. No one else wanted it.',
    'Boom! Username unlocked. Now you’re a legend.',
    'Lucky you. You got the golden ticket, friend.',
    'You nailed it! This username’s now your digital throne.',
    'It’s yours! Like finding the last chocolate bar.',
    'That username’s available. Go ahead, make it your own.',
    'Bam! Username available. It’s like winning the lottery!',
];
export const LANDING_PAGE_HEADING = [
    'Embrace the Chaos, Master the Course. 📚🔥',
    'Your Virtual Campus, Your Rules. 🎓😎',
    'Procrastinate Together, Achieve More (Maybe). 🦥⏰',
    'Study Smarter, Not Harder. (Or Just Have Fun.) 🧠🥳',
    'Level Up Your Learning Game. 🚀🎮',
    'Your All-In-One Study Hub. 🌐💡',
    'Beyond Books and Notes. 📚📈',
    'Where Learning Meets Community. 🧑‍🤝‍🧑',
    'Your Digital Study Squad, Awaits. 👥💻',
    'Redefine Your Study Routine. 🔄📖',
];

export const LANDING_PAGE_DESCRIPTION = [
    'Tired of endless textbooks and boring lectures?',
    'Join a community of like-minded students.',
    'Find study buddies, share notes, and ace your exams.',
    'Access a wealth of study resources and tips.',
    'Make learning fun and engaging.',
    'Your one-stop shop for all your study needs.',
    'Level up your academic journey with ease.',
    'Break free from traditional learning methods.',
    'Discover a new way to learn and connect.',
    'Your future starts here.',
];

export const IDENTITIES = [
    'Agile Fox',
    'Wise Owl',
    'Mighty Lion',
    'Stealthy Panther',
    'Playful Dolphin',
    'Majestic Eagle',
    'Graceful Swan',
    'Cuddly Panda',
    'Speedy Cheetah',
    'Clever Monkey',
    'Loyal Dog',
    'Curious Cat',
    'Strong Bear',
    'Gentle Giraffe',
    'Sly Raccoon',
    'Brave Wolf',
    'Sneaky Snake',
    'Magnificent Tiger',
    'Silent Owl',
    'Powerful Elephant',
];
